require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.0'

target 'syoutube' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVolumeController', :path => '../node_modules/react-native-volume-control'

  target 'syoutubeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'syoutube-tvOS' do
  # Pods for syoutube-tvOS

  target 'syoutube-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
